spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryV5
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
